### PR TITLE
modify 'auto-config' configuration #159

### PR DESCRIPTION
**Pull request by btsatoutkzy**
Please review #159.

### CODE REVIEW

**Comment by btshimizukza** [comment]
@btsatoutkzy 

Please resolve conflicts.

**Comment by btsatoutkzy** [comment]
@btshimizukza 

resolve conflicts. #159

**Comment by kazuki43zoo** [comment]
@btsatoutkzy 

please resolve #164 via this PR.

**Comment by btsatoutkzy** [comment]
@btshimizukza
add  <sec:logout/> #159.

**Comment by btsatoutkzy** [comment]
modify 'sec:logout' position #159.

**Pull request merged**
